const fruits = [
  { id: 1, name: "Apple", emoji: "🍎", color: "Red", isSweet: true, stock: 45 },
  { id: 2, name: "Lemon", emoji: "🍋", color: "Yellow", isSweet: false, stock: 12 },
  { id: 3, name: "Blueberry", emoji: "🫐", color: "Blue", isSweet: true, stock: 150 },
  { id: 4, name: "Avocado", emoji: "🥑", color: "Green", isSweet: false, stock: 8 },
  { id: 5, name: "Mango", emoji: "🥭", color: "Orange", isSweet: true, stock: 22 },
  { id: 6, name: "Banana", emoji: "🍌", color: "Yellow", isSweet: true, stock: 85 },
  { id: 7, name: "Strawberry", emoji: "🍓", color: "Red", isSweet: true, stock: 60 },
  { id: 8, name: "Grapes", emoji: "🍇", color: "Purple", isSweet: true, stock: 40 },
  { id: 9, name: "Watermelon", emoji: "🍉", color: "Green", isSweet: true, stock: 15 },
  { id: 10, name: "Orange", emoji: "🍊", color: "Orange", isSweet: true, stock: 55 },
  { id: 11, name: "Pineapple", emoji: "🍍", color: "Yellow", isSweet: true, stock: 18 },
  { id: 12, name: "Peach", emoji: "🍑", color: "Pink", isSweet: true, stock: 30 },
  { id: 13, name: "Cherry", emoji: "🍒", color: "Red", isSweet: true, stock: 100 },
  { id: 14, name: "Kiwi", emoji: "🥝", color: "Brown", isSweet: true, stock: 42 },
  { id: 15, name: "Pear", emoji: "🍐", color: "Green", isSweet: true, stock: 25 },
  { id: 16, name: "Coconut", emoji: "🥥", color: "Brown", isSweet: true, stock: 10 },
  { id: 17, name: "Pomegranate", emoji: "🍎", color: "Red", isSweet: true, stock: 20 },
  { id: 18, name: "Melon", emoji: "🍈", color: "Green", isSweet: true, stock: 12 },
  { id: 19, name: "Tangerine", emoji: "🍊", color: "Orange", isSweet: true, stock: 48 },
  { id: 20, name: "Lime", emoji: "🍋‍🟩", color: "Green", isSweet: false, stock: 35 },
  { id: 21, name: "Grapefruit", emoji: "🍊", color: "Pink", isSweet: false, stock: 14 },
  { id: 22, name: "Raspberry", emoji: "🍓", color: "Red", isSweet: true, stock: 90 },
  { id: 23, name: "Papaya", emoji: "🥭", color: "Orange", isSweet: true, stock: 11 },
  { id: 24, name: "Dragon Fruit", emoji: "🌵", color: "Pink", isSweet: true, stock: 9 },
  { id: 25, name: "Apricot", emoji: "🍑", color: "Orange", isSweet: true, stock: 33 },
  { id: 26, name: "Plum", emoji: "🟣", color: "Purple", isSweet: true, stock: 28 },
  { id: 27, name: "Fig", emoji: "🍷", color: "Purple", isSweet: true, stock: 16 },
  { id: 28, name: "Blackberry", emoji: "🫐", color: "Black", isSweet: true, stock: 75 },
  { id: 29, name: "Cantaloupe", emoji: "🍈", color: "Orange", isSweet: true, stock: 13 },
  { id: 30, name: "Guava", emoji: "🍐", color: "Green", isSweet: true, stock: 19 },
  { id: 31, name: "Passion Fruit", emoji: "🟣", color: "Purple", isSweet: false, stock: 24 },
  { id: 32, name: "Lychee", emoji: "🔴", color: "Red", isSweet: true, stock: 50 },
  { id: 33, name: "Persimmon", emoji: "🍅", color: "Orange", isSweet: true, stock: 17 },
  { id: 34, name: "Cranberry", emoji: "🍒", color: "Red", isSweet: false, stock: 120 },
  { id: 35, name: "Date", emoji: "🫘", color: "Brown", isSweet: true, stock: 200 },
  { id: 36, name: "Jackfruit", emoji: "🌳", color: "Green", isSweet: true, stock: 5 },
  { id: 37, name: "Starfruit", emoji: "⭐", color: "Yellow", isSweet: true, stock: 14 },
  { id: 38, name: "Durian", emoji: "🦔", color: "Green", isSweet: true, stock: 3 },
  { id: 39, name: "Clementine", emoji: "🍊", color: "Orange", isSweet: true, stock: 65 },
  { id: 40, name: "Mulberry", emoji: "🍇", color: "Black", isSweet: true, stock: 40 },
  { id: 41, name: "Kumquat", emoji: "🟠", color: "Orange", isSweet: false, stock: 22 },
  { id: 42, name: "Rhubarb", emoji: "🪴", color: "Red", isSweet: false, stock: 18 },
  { id: 43, name: "Gooseberry", emoji: "🟢", color: "Green", isSweet: false, stock: 30 },
  { id: 44, name: "Plantain", emoji: "🍌", color: "Green", isSweet: false, stock: 25 },
  { id: 45, name: "Elderberry", emoji: "🫐", color: "Purple", isSweet: false, stock: 80 },
  { id: 46, name: "Quince", emoji: "🍏", color: "Yellow", isSweet: false, stock: 12 },
  { id: 47, name: "Rambutan", emoji: "🔴", color: "Red", isSweet: true, stock: 45 },
  { id: 48, name: "Longan", emoji: "⚪", color: "Brown", isSweet: true, stock: 38 },
  { id: 49, name: "Olive", emoji: "🫒", color: "Green", isSweet: false, stock: 300 },
  { id: 50, name: "Tomato", emoji: "🍅", color: "Red", isSweet: true, stock: 110 }
];

export default fruits;